# project informations for Bukkit in order to register our plugin with all it components
# ${-} are variables from Maven (pom.xml) which will be replaced after the build
name: ${project.name}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}.${project.name}

# meta informations for plugin managers
authors: [games647, 'https://github.com/games647/LagMonitor/graphs/contributors']
description: |
    ${project.description}
website: ${project.url}
dev-url: ${project.url}

commands:
    ping:
        description: 'Gets the ping of the selected player'
        usage: '/<command> [player]'
    stacktrace:
        description: 'Gets the execution stacktrace of selected thread'
        usage: '/<command> [threadName]'
    thread:
        description: 'Outputs all running threads with their current state'
        usage: '/<command> [threadName]'
    tpshistory:
        description: 'Outputs the current tps'
        aliases: [tps]
    mbean:
        description: 'Outputs mbeans attributes (java environment information)'
        aliases: [bean]
        usage: '/<command> [beanName] [attribute]'
    system:
        description: 'Gives you some general information about your server like free ram, or cpu usage'
    timing:
        description: 'Outputs your server timings ingame'
    monitor:
        description: 'Monitors the CPU usage of methods'
    graph:
        description: 'Gives you visual graph about your server'